---
title: "p8105_hw2_zz3168"
author: "Zixuan Zhang"
date: "2023-10-02"
output: github_document
---

### Problem 0

```{r}
library(tidyverse)
library(readxl)
```

### Problem 1
```{r clean_538_plots}
month_df = tibble(
    month_num = 1:12,
    month_abb = month.abb,
    month = month.name
  )
 
pols = 
  read_csv("data/pols-month.csv") |> 
  separate(mon, into = c("year", "month_num", "day"), convert = TRUE) |> 
  mutate(president = recode(prez_gop, "0" = "dem","1" = "gop", "2" ="gop" )) |>
  left_join(x = _, y = month_df) |> 
  select(year, month, everything(), -day, -starts_with("prez"))
  
  
```

We also clean the 538 `snp` data, which contains information related to Standard & Poor’s stock market index.

```{r clean_538_snp}
snp = 
  read_csv("data/snp.csv") |> 
  separate(date, into = c("month", "day", "year"), convert = TRUE) |> 
  arrange(year, month) |> 
  mutate(month = month.name[month]) |>
  select(year, month, close)
  
```

we tidy the `unemployment` data so that it can be merged with the `pols` and `snp` datasets.